#!/bin/sh

set -e

cd "$(dirname "$0")/../.."
fmt_venv="$PWD/.fmt/venv"

set +e
changed_python="$(git diff --cached --name-only --diff-filter=ACMR | grep "\.py$")"
set -e

. "$fmt_venv/bin/activate"

if [ -n "$changed_python" ]; then
  echo "$changed_python" | tr "\n" "\0" | xargs -0 black -t py37 -l 100
  echo "$changed_python" | tr "\n" "\0" | xargs -0 git add
fi

deactivate
